"""change cashier phone number field

Revision ID: 1d313e842b4e
Revises: d2336dc04b2e
Create Date: 2022-07-28 19:49:12.692274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d313e842b4e'
down_revision = 'd2336dc04b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cashiers', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashiers', type_='unique')
    # ### end Alembic commands ###
